### ISSUE TITLE
cannot use "require" to load firebase-token-generator

### ISSUE THREAD

**Issue by nathanallen** [ccslakey/wdifinal#3]
see `app/auth-vars.js:1`

Remove node style "require" from `auth-vars.js`. You are already using bower to load firebase-token-generator (see `app/index.html`).

Once removed, `FirebaseTokenGenerator#createToken` method will throw an error because it is being passed an integer instead of a string (see `app/auth-vars.js:3`)

```
Uncaught Error: FirebaseTokenGenerator.createToken failed: First argument must contain a "uid" key that must be a string.
```

Example code can be found here: https://github.com/firebase/firebase-token-generator-node#generating-tokens

**Comment by ccslakey** [comment]
fixed
